- backend/internal/errs/http_error.go
- backend/internal/service/server.go
Added central error handling logic. Fiber will delegate to ErrorHandler if error is thrown by handler. More error functions should be added as necessary
> feat: add central error handling

- frontend/.eslintrc.js
- frontend/package-lock.json
- frontend/package.json
> Test lint fix

- backend/internal/supabase/migrations/20240917002108_base_schema.sql
- backend/internal/supabase/migrations/20240922222648_add_rest_of_schema.sql
- backend/internal/supabase/seed.sql
> Rest of schema

- backend/go.mod
- backend/internal/service/handler/reviews/get_media_reviews.go
- backend/internal/service/server.go
- backend/internal/storage/postgres/schema/review.go
- backend/internal/storage/storage.go
New PR for getting reviews by album and track id with hopefully less conflicts
> Get reviews less conflicts

- backend/Dockerfile
> Certificate fix maybe

- backend/Dockerfile
> cert fix fer sure

- docs/Schema.md
This updates the migration docs to be more accurate and to explain how to test locally
> Update migration docs

- backend/internal/models/media.go
- backend/internal/service/handler/media/get_media.go
- backend/internal/service/utils/pagination.go
- backend/internal/storage/postgres/schema/media.go
- backend/internal/storage/storage.go
> Get most discussed media

- backend/internal/supabase/migrations/20241020050459_add_entusiasm_to_users.sql
- backend/internal/supabase/migrations/20241020051851_addition_of_tags.sql
- backend/internal/supabase/seed.sql
[Link to Ticket](https://github.com/GenerateNU/platnm/issues/86#issue-2581488413)
Completed But Tags need to be updated based on whatever Design has come up with
Enthusiasm Column Addition
Tags
> Update schema tags and enthusiasm

- nix_modules/devenv.nix
adds a new command to the nix menu pallet to run the frontend properly via tunnel. I think for the windows ppl they might need to download ngrok but it'll prompt them to do so.
i ran it and it worked
> 9000 story point ticket - new nix command to run via tunnel 

- backend/internal/storage/postgres/schema/media.go
- backend/internal/storage/postgres/schema/review.go
- frontend/app/(tabs)/profile.tsx
- frontend/app/MediaPage.tsx
- frontend/app/PreviewReview.tsx
- frontend/components/ReviewCard.tsx
- frontend/components/SongCard.tsx
- frontend/hooks/usePublishReview.ts
This PR makes tiny changes to ensure general styling consistency and fake data consistency.
https://github.com/user-attachments/assets/fb44baee-46f4-42bd-8b5a-f67aeba5e6fd
> make all-hands demo experience more interesting

- frontend/app/MediaPage.tsx
- frontend/babel.config.js
- frontend/components/media/Histogram.tsx
- frontend/package-lock.json
- frontend/package.json
Adds histogram to the rating page to show distribution of ratings
[Link to Ticket](https://github.com/GenerateNU/platnm/issues/102)
> Review histogram!

- backend/internal/models/recommendation.go
- backend/internal/storage/postgres/schema/recommendation.go
Adds more fields to the recommendations endpoint to power the frontend
> Make recommendations endpoint cooler

- backend/internal/models/review.go
- backend/internal/service/handler/reviews/get_social_reviews.go
- backend/internal/service/server.go
- backend/internal/storage/postgres/schema/review.go
- backend/internal/storage/storage.go
Created two endpoints:
- One is for media type album and the other is for media type track.
- Both retrieve the number of times a user reviewed a piece of media, and the friends review data for that piece of media (rating, comment, name, @), where 'friends' is defined as the set of users that the specified user follows.
Created two routes: 
GET /reviews/social/album/:albumid
GET /reviews/social/song/:songid
Both endpoints take a required query parameter 'userid' that is the id of the specified user. I created one function 'GetSocialReviews' on a review handler that is parameterized by media type. 
JSON return format:
{
"ratingCount": 1,
"friendReviews": [
{
"rating": 10,
"comment": "hi",
"display_name": "Jane Eyre",
"username": "jane_eyre"
}
]
}
GetSocialReviews in the schema package will …
> Get Social Reviews

- backend/internal/service/handler/reviews/get_comments.go
- backend/internal/service/server.go
- backend/internal/storage/postgres/schema/review.go
- backend/internal/storage/storage.go
> Get review comments

- frontend/app/(tabs)/index.tsx
- frontend/app/(tabs)/search.tsx
- frontend/app/Recommendations.tsx
- frontend/app/_layout.tsx
> refactor: move recommendations page to music button

- backend/internal/storage/postgres/schema/user.go
- frontend/app/(tabs)/login.tsx
- frontend/app/(tabs)/profile.tsx
> Reroute unauthenticated

- frontend/app/(tabs)/login.tsx
- frontend/app/onboarding/signup.tsx
failed api requests dont make onboarding advance to next page. also tapping on screen while keyboard is up closes keybaord
> fix onboarding bugs

- backend/internal/service/handler/users/section.go
- backend/internal/storage/postgres/schema/user.go
- frontend/app/(tabs)/profile.tsx
- frontend/components/profile/SelectSection.tsx
> Fixed profile getters on profile page

- backend/internal/models/profile.go
- backend/internal/service/handler/spotify/import_artist_details.go
- backend/internal/service/handler/users/user.go
- backend/internal/service/middleware/spotify/spotify.go
- backend/internal/service/server.go
- backend/internal/storage/postgres/schema/media.go
- backend/internal/storage/storage.go
localhost:8080/spotify/clientCreds/import/artist-details
endpoint is working. call the above route
> import artist photos from spotify

- frontend/app/(tabs)/index.tsx
- frontend/app/(tabs)/profile.tsx
- frontend/app/(tabs)/search.tsx
- frontend/app/Activity.tsx
- frontend/app/CreateReview.tsx
- frontend/app/MediaPage.tsx
- frontend/app/OnQueue.tsx
- frontend/app/ReviewPage.tsx
- frontend/components/AuthProvider.tsx
- frontend/components/CommentComponent.tsx
- frontend/components/ReviewPreview.tsx
- frontend/components/media/MediaCard.tsx
- frontend/components/media/RatingSlider.tsx
- frontend/components/media/YourRatings.tsx
- frontend/components/profile/ProfilePicture.tsx
- frontend/components/profile/SectionItem.tsx
- frontend/hooks/usePublishReview.ts
- frontend/package-lock.json
- frontend/package.json
replaces hardcoded userIds throughout in favor of useAuthContext()
leaves john doe as the default so you can still develop locally without needing to sign in
also makes a few styling changes / fixes that i noticed throughout
> use auth context throughout

- frontend/app/(tabs)/search.tsx
[Link to Ticket](https://github.com/GenerateNU/platnm/issues/180#issue-2696098576)
> sticky search

- backend/internal/supabase/migrations/20241130181441_add_platnm.sql
[Link to Ticket](https://github.com/GenerateNU/platnm/issues/192)
tested locally and platnm column was added
> add platnm column

- backend/internal/models/user.go
- backend/internal/service/handler/users/get_connections.go
- backend/internal/service/server.go
- backend/internal/storage/postgres/schema/user.go
- backend/internal/storage/storage.go
working on a version that leverages concurrency, but this works too. prob wont be able to work again for a couple days so if you wanna get this merged i can make another PR later to add the concurrency
> Get followers and following endpoint

- backend/internal/service/handler/reviews/get_media_reviews.go
- frontend/app/MediaReviewsPage.tsx
- frontend/assets/images/media-vinyl.svg
- frontend/components/media/YourRatings.tsx
[Link to Ticket](https://github.com/GenerateNU/platnm/issues/182#issue-2696204817)
> adding the stats to the media review page

- backend/cmd/server/main.go
- backend/internal/service/server.go
- backend/internal/storage/postgres/storage.go
- backend/internal/storage/storage.go
> fix setup and close db

- backend/internal/config/db.go
- backend/internal/models/preview.go
- backend/internal/models/review.go
- backend/internal/storage/postgres/schema/review.go
- backend/internal/storage/postgres/schema/user.go
- backend/internal/storage/postgres/storage.go
- backend/internal/supabase/migrations/20241203045109_add_review_title.sql
- frontend/app/(tabs)/user.tsx
- frontend/app/CreateRating.tsx
- frontend/app/CreateReview.tsx
- frontend/app/MediaPage.tsx
- frontend/app/_layout.tsx
- frontend/components/NudgePage.tsx
- frontend/components/ReviewPreview.tsx
- frontend/components/media/MediaCard.tsx
- frontend/components/media/Tag.tsx
- frontend/components/media/TagSelector.tsx
- frontend/components/media/YourRatings.tsx
- frontend/hooks/usePublishReview.ts
- frontend/types/types.ts
Updates rating flow to mostly match newest version made by @abhikaboy 
Also updates database schema + queries to include optional review title column and incorporates this into FE
Can made additional styling changes in followup PR but this one's getting big and involves BE changes
> Update rate flow

- backend/internal/constants/platnm.go
- backend/internal/storage/postgres/schema/playlist.go
- backend/internal/storage/postgres/schema/recommendation.go
- backend/internal/storage/postgres/schema/review.go
- backend/internal/storage/postgres/schema/user.go
- frontend/hooks/useProfile.ts
> Added Platnm to users

- frontend/components/media/MediaCard.tsx
let users add to their on queue from the media page
https://github.com/user-attachments/assets/ad0d0657-d2df-40c7-aff4-9fe4d1ab1435
> allow users to add to on queue from song page
